[SPR-40] feat: 암장 루트 생성/조회 구현
TheClimeet/climeet-spring pull request #19
Opened 2024-01-13 05:53 UTC by Nesquitto

## 요약

- 기존에 개발 완료된 사항에서 수정했습니다.

## 상세 내용

- 이전 PR 에서 수정 요청사항을 반영했습니다.
>-  Swagger 설명을 추가했습니다.
>- ColumnDefault를 Sector의 Floor에 적용했습니다.
>기존의 ```floor = 0```과 다른점은 ColumnDefault는 테이블 생성시에 컬럼 자체에 옵션을 추가하는 것이며, ```floor = 0```은 테이블에 데이터를 삽입할 때 입력된 값이 없으면 추가하는 것으로 이해했습니다.
>- RouteController에 RequestMapping을 적용했습니다.
>- RouteService에 createRoute에서 RouteCreateRequestDto를 바로 받아서 사용하도록 적용했습니다.

- 예외처리를 추가했습니다.
>- Sector 데이터가 Empty일 때 예외처리 추가했습니다.
>- Parameter로 받은 gymId값이 Sector에 저장된 gymId와 일치하지 않을 때 예외처리 추가했습니다.
>- Route 데이터가 Empty일 때 예외처리 추가했습니다.
>- Route List를 불러왔을 때 값이 없으면 에러 반환하도록 예외처리 추가했습니다.

- RouteController에서 MultiPart 이미지 파일을 받아서 S3에 올리도록 추가했습니다.
>- Postman에서 같은 JSON인데 인식을 못해서 몇시간동안 끙끙대다가 해결했습니다.

## 테스트 확인 내용

- Notion API 문서에 수정사항 반영하겠습니다.
 <img width="654" alt="스크린샷 2024-01-13 오후 2 49 11" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/4702d765-6d02-4683-a4a3-9c671e7f81bd">
DB 확인했고, 이미지 잘 올라간 것 확인했습니다.
- 각 예외상황에 맞는 값 입력해서 확인 완료했습니다.

## 질문 및 이외 사항
- RouteCreateRequestDto로 Dto 클래스를 사용하고 있는데, 쇼츠 업로드 API와 Dto 형식을 맞추는게 나을 것 같아 value 값으로 routeCreatePostReq를 사용하도록 했습니다. 추후 내부 형식이 정립되면 수정하겠습니다.
- 암장 정보 부분도 열심히 작업중입니다! 작업 완료되면 또 PR 날리러 오겠습니다!

2024-01-13 10:48 UTC, tjdgns8439 approved these changes
LGTM!

2024-01-13 15:33 UTC, gourderased requested changes
고생하셨습니다! 코멘트단 부분 확인해주세욥~!!

2024-01-13 15:33 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/sector/Sector.java
> +    private int floor;
@ColumnDefault의 역할은 ddl-auto가 create 혹은 create-drop으로 설정될때만 적용됩니다! 저도 항상 @ColumnDefault만 사용하다가 이번에는 클래스에서 값을 주입하는 형식으로 엔티티를 매핑했는데 둘의 장단이 있는 것 같습니다!
- @ColumnDefault 사용 : 데이터베이스 스키마에서 더미값을 넣어줄때 편리함, 또한 @ColumnDefault 사용시에는 @DynamicInsert 어노테이션도 붙여야합니다! [@DynamicInsert](https://velog.io/@choidongkuen/JPA-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-DynamicInsert-DynamicUpdate-%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B4%85%EC%8B%9C%EB%8B%A4)
- 클래스 주입 : 더미값 삽입시 불편하지만 빌더에서 해당 필드를 명시해주지 않아도됨, ddl이 create가 아닐때도 바로 사용할 수 있음

일단 저희가 ddl을 validate으로 바꾸었기 때문에 ColumnDefault를 적용하기 위해서는 @DynamicInsert 어노테이션도 추가후에 테이블을 create전부 다시 생성해야합니다! 
원래대로 생성자 주입으로 바꾸는것이 좋아보입니다~!

2024-01-13 15:33 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        }
루트 생성화면의 경우 암장정보와 섹션Id를 먼저 프론트쪽으로 넘겨주고 프론트에서 루트를 생성할 때 받은 gymId와 섹션 Id를 넘겨주기 때문에 이 부분은 예외처리를 하지 않아도 될 것 같은데 혹시 제가 생각못한 부분이 있을까요? 어떻게 생각하시나요!

2024-01-13 15:33 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/route/dto/RouteRequestDto.java
> +        private Integer difficulty;
여기 Integer를 사용하신 이유가 있을까요?

2024-01-13 16:38 UTC, tjdgns8439 approved these changes

2024-01-13 16:38 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        }
지운님 의견에 동의합니다~!

2024-01-13 16:38 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/route/dto/RouteRequestDto.java
> +        private Integer difficulty;
혹시 제 저번 PR에서 제가 맡은 RouteRecord, ClimbingRecord에 해당하는 int 필드를 Integer로 바꾸었기 때문일까요?

저 같은 경우 아직 변경사항을 push하지는 않았지만 제가 Integer로 바꾸었었던 값들을 모두 int값으로 변경해주었습니다...^^(죄송합니다.)

대신 dto에서는 조금 변경이 있습니다.

<img width="393" alt="스크린샷 2024-01-14 오전 1 27 03" src="https://github.com/TheClimeet/climeet-spring/assets/100510247/031afbe7-a770-48b8-ad09-5c4a4b05fdd8">
보시는 것처럼 RouteRecord를 생성할 때와 수정할 때 attemptCount의 타입이 다릅니다.
저는 이 부분에서 int와 Integer의 차이를 고려했습니다.
- int는 요청 dto에 해당 값이 없다면 0을 반환합니다.
- Integer는 요청 dto에 해당 값이 없다면 null을 반환합니다.

PostRouteRecordDot의 경우입니다.(생성)
- 고객이 도전할 예정인 루트에 대해서 기록을 남기고 싶을 경우를 고려하였습니다. (논리적으로 도전하지 않은 루트는 생성하는 것이 맞을 수도 있지만)
- 이 경우 생성 로직에서는 만약 Dto에 attemptCount에 대한 값이 담겨있지 않더라도 자동으로 0을 넣을 수 있도록 int로 타입을 설정하였습니다.

PatchRouteRecordDto의 경우입니다. (수정)
- 클라이언트에서 변경할 값만 요청하고 attemptCount에 대해서는 변경하지 않을 값으로 설정하기 위해 해당 값을 dto에 담겨보내지 않을 수 있습니다.
- 이 때 int라면 0을 반환합니다.
- 하지만 위 상황과 마찬가지로 고객이 해당 기록의 시도횟수를 의도적으로 0으로 보낼 경우를 대비하여 or 클라이언트에서 의도한 값이 0인 경우를 고려하여 값이 없으면 null을 반환하는 Integer를 선택하였습니다.
(만약 의도적으로 0으로 설정하면 삭제하거나 아니면 그냥 두거나 하는 방향은 추후에 API 연결할 때 상의하는 것이 좋을 것 같습니다.)

만약 제가 잘못 알고 있는 지식이 있거나 비효율적이라면 말씀해주시면 감사하겠습니다!
지나가다 피드백을 보고 들렸는데 동식님이 다른 의도가 있었다고 하면 계속해서 지나가겠습니다!

2024-01-14 06:04 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/sector/Sector.java
> +    private int floor;
확인했습니다! 변경하겠습니당

2024-01-14 06:50 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        }
필요없을 것 같습니다! 수정하겠습니다!

2024-01-14 06:53 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/route/dto/RouteRequestDto.java
> +        private Integer difficulty;
이런 차이를 고려하는 코딩이라니... 멋집니다! 저는 단순히 모두 래퍼 클래스로 통일성을 부여하는게 좋겠다는 생각이었습니다! 두 차이 숙지해서 앞으로 더 나은 코딩 하겠습니다!

2024-01-14 07:37 UTC, yerim216 approved these changes
고생하셨습니다!
다른 분들 리뷰 보고 저도 많이 배워가네요 :~)
@ColumnDefault는 제가 지난 pr에 남겼는데 무작정 쓰던 허점을 들켜버렸네요 .. 허허..

2024-01-15 10:32 UTC, Nesquitto commented
악 DTO 통일하겠습니다!

2024-01-15 11:39 UTC, Nesquitto commented
Dto 컨벤션 수정 및 toEntity로 변경 완료했습니다!

2024-01-16 08:51 UTC, gourderased approved these changes

2024-01-16 08:52 UTC, merged