[SPR-54] feat: 운동기록 수정&삭제 구현
TheClimeet/climeet-spring pull request #21
Opened 2024-01-15 07:26 UTC by tjdgns8439

## 요약
- ClimbingRecord 수정&삭제 구현
- RouteRecord 수정&삭제 구현
- 이번주 best(암장, 루트, 클라이머) 관련 필드 추가
- 예외처리
- requestDto 내부 클래스로 수정
- onDelete 어노테이션 적용

## 상세 내용
### ClimbingRecord 수정&삭제 구현
```java
ClimbingRecordService.java
    클라이밍 기록을 업데이트 하는 함수입니다.
    클라이밍 기록 자체에서 업데이트 할 수 있는 값은 운동날짜와 운동시간입니다.
    public ClimbingRecordSimpleInfo updateClimbingRecord(Long id,
        PatchClimbingRecordDto requestDto) {(생략)}
    
    클라이밍 기록을 삭제하는 함수입니다.
    정상적으로 삭제가 완료되면 "클라이밍기록이 삭제되었습니다."라는 문구를 반환합니다.
    public ApiResponse<String> deleteClimbingRecord(Long id) {(생략)}
```

### RouteRecord 수정&삭제 구현
```java
RouteRecordService.java

    루트기록을 업데이트하는 함수입니다.
    해당 루트기록의 수정사항을 고려하여 이와 연관된 ClimbingRecord의 필드값도 함께 수정합니다.
    수정되는 ClimbingRecord의 필드는 attemptCount, totalCompletedCount, avgDifficulty입니다.
    @Transactional
    public RouteRecordSimpleInfo updateRouteRecord(Long id, PatchRouteRecordDto patchRouteRecordDto) {(생략)}
     
    루트기록을 삭제하는 함수입니다.
    업데이트와 마찬가지로 삭제를 하며 ClimbingRecord의 attemptCount, totalCompletedCount, avgDifficulty를 업데이트합니다.
    @Transactional
    public ApiResponse<String> deleteRouteRecord(Long id) {(생략)}
    
    각 루트가 업데이트 될 때 운동기록에 새로 설정해줘야 하는 평균값을 계산하는 함수입니다.
    (oldCount - 1 )이 0이라면  ArithmeticException 에러가 발생하기 때문에 if(oldCount <= 1) return 0 으로 예외처리를 해주었습니다.
    public int newAvgDifficulty(int routeDifficulty, int oldAvgDifficulty, int oldCount,
        boolean isPlus) {
        if (isPlus) {
            return (int) (((oldCount * oldAvgDifficulty) + routeDifficulty) / (oldCount + 1));
        } else {
            if(oldCount <= 1) return 0;
            else return (int) (((oldCount * oldAvgDifficulty) - routeDifficulty) / (oldCount - 1));
        }
    }
```

### 이번주 best(암장, 루트, 클라이머) 관련 필드 추가
```java
User.java

    private int thisWeekCompleteCount = 0;

    private Long thisWeekTotalClimbingTime = 0L;

    private int thisWeekHighDifficulty = 0;
```
```java
Route.java

    private int selectionCount = 0;

    private int thisWeekShortsTagCount = 0;
```
```java
Climbing.java

    private int thisWeekFollowerCount = 0;

    private int thisWeekSelectionCount = 0;
```
### 예외처리
```java
    //운동 기록 관련
    _EMPTY_CLIMBING_RECORD(HttpStatus.CONFLICT, "CLIMBING_RECORD_001", "존재하지 않는 암장운동기록입니다."),
    _INVALID_DATE_RANGE(HttpStatus.CONFLICT, "CLIMBING_RECORD_002",
        "시점상 시작 날짜는 종료 날짜보다 같거나 앞서야 합니다."),

    //루트 기록 관련
    _EMPTY_ROUTE_RECORD(HttpStatus.CONFLICT, "ROUTE_RECORD_001", "존재하지 않는 루트운동기록입니다.");

```

## 테스트 확인 내용
- 각 수정과 삭제 로직이 정상적으로 작동하는 것을 로컬db에서 확인하였습니다.

## 질문 및 이외 사항
- User, ClimbingGym, Shorts, Route 관련 파트를 맡은 분들은 service 계층에서 해당 필드들을 수정해주시기 바랍니다!
- 다음부터는 PR 단위를 보다 세부적으로 끊겠습니다~

2024-01-15 08:21 UTC, gourderased requested changes
복잡한 부분을 잘 처리해주셨습니다! 컨벤션 맞추면서 수정도 하시느라 고생도 하셨네요 ㅎ 이번 컨벤션에 따라 한번더...수정해주시면 너무~ 좋아요ㅎㅎㅎ
리뷰 확인해주시고 수정해주세요~!

2024-01-15 08:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routerecord/RouteRecordService.java
> +            .orElseThrow(() -> new GeneralException(ErrorStatus._EMPTY_ROUTE));
try catch보다 코드가 훨씬 간결해졌네용 굳굳!!

2024-01-15 08:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routerecord/RouteRecordService.java
> +    }
예외까지 처리해서 너무 잘 작성해주셨네요! null처리에 대한 부분은 어제 회의에도 얘기한 @DynamicUpdate확인해보시면 좋을 것 같습니다 그리고 지금 코드로만 봤을때 `루트 수정`이라는 메소드안에 한가지가 아닌 두가지 기능이 있는걸로 보입니다! 
새 값과 db에 있는 기존 값 변경은 따로 private 메소드로 빼서 분리하는 것이 좋아보입니다!

- updateRecord
```java
updateRecord() {
    //각 필드의 기존값들
        Long oldRouteId = routeRecord.getRoute().getId();
        int oldAttemptTime = routeRecord.getAttemptCount();
        Boolean oldIsCompleted = routeRecord.getIsCompleted();

        //각 필드의 새값들
        Long newRouteId = patchRouteRecordDto.getRouteId();
        Integer newAttemptTime = patchRouteRecordDto.getAttemptCount();
        Boolean newIsComplete = patchRouteRecordDto.getIsComplete();
        
        updateOldValues(newRouteId, newAttempt.... , oldCompleted, climbingRecord);
        
        return new ...
}
```

- updateOldValues
```java
private void updateOldValues(Long newRouteId... , ClimbingRecord climbingRecord) {
    //null검증 처리하면서 값 바꿔주기
}
```

2024-01-15 08:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routerecord/RouteRecordService.java
> +    public int newAvgDifficulty(int routeDifficulty, int oldAvgDifficulty, int oldCount,
수정과 삭제 모두 이용하도록 잘 처리해주셨습니다!

2024-01-15 11:24 UTC, Nesquitto approved these changes
복잡한 로직을 아주 멋들어지게 구성한거 정말 멋집니다!!

그리고... toEntity! 까먹고 있다가 발견합니다... 수정하러 이만 총총...

수고하셨습니다!!

2024-01-16 15:43 UTC, yerim216 approved these changes
운동기록 복잡한데 코드 깔끔하게 잘 작성하신 것 같아요!
근데 띄어쓰기로 코드 변경사항이 많이진 것 같은데 들여쓰기 컨벤션을 바꾸신건가요?
고생하셨습니다!

2024-01-16 15:50 UTC, gourderased approved these changes

2024-01-16 15:51 UTC, merged