[SPR-38] 관리자 회원가입 기능 구현(암장 조회, 검색 기능 제외)
TheClimeet/climeet-spring pull request #24
Opened 2024-01-15 17:26 UTC by yerim216

## 요약

-암장 조회, 검색 기능을 제외한 관리자 회원가입 기능을 구현하였습니다
(관리자 ID 중복검사 API, 관리자-암장 1:1 관계로, 이미 암장에 관리자가 배정 되어있는지 확인하는 API)

## 상세 내용

- Manager와 ClimbingGym과 연관관계를 추가하였습니다
기존에 연관관계가 빠져있어서, 1대1 연관관계 매핑하는 어노테이션을 추가하였고, 연관관계 주인은 ClimbingGym으로 설정하였습니다(ClimbingGym 테이블에 Manager 인덱스 저장)

Manager.java
> @Setter
>     @OneToOne
>     @JoinColumn(name="id")
>     private ClimbingGym climbingGym;

ClimbingGym.java
> @OneToOne
>     @JoinColumn(name="manager_id")
>     private Manager manager;

- 구현한 API 
  /**
     * [POST] 관리자 회원가입 API
     */
    @PostMapping("/signup")
    public ResponseEntity<Manager> signUp(@RequestBody
        CreateManagerRequest createManagerRequest){

    /**
     * [GET] 암장 관리자 등록 여부 확인
     */
    @GetMapping("/isRegistered/{gymName}")
    public ResponseEntity<Boolean> isRegistered(@PathVariable String gymName)

    /**
     * [GET] 관리자 ID 중복확인
     */
    @GetMapping("/check-id/{loginId}")
    public ResponseEntity<Boolean> checkLoginId(@PathVariable String loginId)

-toEntity 관련?
훈이 작성한 코드를 참고해서 작성했는데, Entity 내부에 toEntity 함수가 있어서 저도 처음에 Entity 내부에 toEntity 함수를 작성하고 Service에서 가져다 쓰려고 했습니다. 
근데 회원가입 시 Manager 엔티티 외의 다른 엔티티(ex : 알림 설정 여부-User, 암장 배경사진 - ClimbingBackgroundImage)에 저장되어야 할 정보가 있을 때에는 Manager 엔티티 내부에서 toEntity를 작성하고 가져다 쓰는게 맞지 않다고 생각되고 오류도 생겨서 현재는 Service 단에 toEntity 함수를 작성하고, 가져다쓰는 식으로 구현했습니다. 이에 대해서 다들 어떻게 생각하시는지 궁금합니다!

## 테스트 확인 내용
-swagger를 통해 여러 경우의 수에 해당하는 입력들을 넣어보며 예외 처리를 테스트 했습니다

## 질문 및 이외 사항

- 다른 분들은 테스트 시 로컬 DB를 따로 사용하시나요? 저는 application-dev에 있는 rds를 사용하는데, 다른 분들은 어떻게 사용하시는지 궁금합니다.
- 유저 관련 급한 불을 끄고 TDD도 해보고 싶네요 🥲

2024-01-16 07:04 UTC, gourderased requested changes
확인해주세욥

2024-01-16 07:04 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/ClimberService.java
이 부분 setter사용보다 updateBasicInformation? 같이 클래스에 함수로 작성하는게 좋아보입니다~!
[Setter사용을 왜 지양해야할까](https://velog.io/@hope1213/Setter-%EC%82%AC%EC%9A%A9%EC%9D%84-%EC%99%9C-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C)

2024-01-16 07:04 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerService.java
> +    public boolean isManagerRegistered(String gymName){
함수명은 동사로 작성해주세욥! check같이 앞에 동사를 붙이면 함수역할이 더 직관적으로 보일 것 같습니다!

2024-01-16 07:04 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerService.java
> +        ClimbingGym gym = climbingGymRepository.findByName(gymName);
if문 안 null체크 대신 orElseThrow문으로 체크해주세요!
코드의 가독성이 훨씬 좋아집니다!

2024-01-16 07:04 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerService.java
> +    public boolean isLoginDuplicated(String loginId){
마찬가지입니다! 동사붙여주세욥

2024-01-16 16:04 UTC, tjdgns8439 approved these changes
고생하셨습니다!! 전반적으로 코드가 깔끔합니다!
다만 ApiResponse에 대해서 다시 확인해주세요!(저도 고쳐야합니다ㅜㅜ)

2024-01-16 16:04 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/climber/ClimberService.java
40번라인 주석 지워주세요!

2024-01-16 16:04 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/climber/dto/ClimberRequestDto.java
dto관련 컨벤션 확인 부탁드립니다!

2024-01-16 16:04 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerService.java
> +    public Manager toEntity(CreateManagerRequest createManagerRequest){
toEntity의 위치에 대해 다음 회의 때 의견 나누면 좋을 것 같습니다!
저도 기존에는 Entity에서 toEntity를 구현하였지만 requestDto 단에서 구현해도 좋을 것 같다는 생각을 했습니다.
이 부분에는 정답이 없는 것 같으니 회의 때 정하면 좋을 것 같습니다!
[https://velog.io/@smc2315/DTO-Entity-%EB%B3%80%ED%99%98-%EB%A9%94%EC%84%9C%EB%93%9C-%EA%B5%AC%ED%98%84-%EC%9C%84%EC%B9%98%EB%8A%94-%EC%96%B4%EB%94%94%EA%B0%80-%EC%A2%8B%EC%9D%84%EA%B9%8C](url)

2024-01-17 00:52 UTC, Nesquitto approved these changes
수고하셨습니다! Controller 단에서 질문사항 하나 있습니다! 감사합니다!

2024-01-17 00:52 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(manager);
Controller에서 return을 ApiResponse로 통일을 안해도 되는걸까요?!

2024-01-17 00:52 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/manager/ManagerController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(manager);
아 이미 위에 언급이 되어있네요!!

2024-01-19 09:13 UTC, gourderased approved these changes

2024-01-19 09:18 UTC, merged