[SPR-36] feat: 클라이머 네이버 로그인/회원가입 기능 구현
TheClimeet/climeet-spring pull request #25
Opened 2024-01-16 12:54 UTC by yerim216

## 요약

- 네이버 소셜 로그인 기능, 회원가입 기능을 구현하였습니다. 
- 토큰 입력 방식을 @PathVariable에서 Header로 변경하였습니다. 

## 상세 내용

- 앞서 PR 올렸던 로직에 NAVER 부분을 추가하였습니다
OAuth2UserInfo를 상속받아서 KakaoUserInfo를 구현하였습니다

## 테스트 확인 내용

-실제 access token을 이용해서 테스트 과정을 거쳤습니다

## 질문 및 이외 사항

-

2024-01-16 16:06 UTC, tjdgns8439 approved these changes

2024-01-16 16:06 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/climber/ClimberService.java
try-catch가 아닌 커스텀 ErrorStatus를 반환하게 해주세요!

2024-01-16 19:12 UTC, gourderased requested changes
우디한테 회초리 맞느라 고생하셨습니다 ㅎㅎㅎ 
수정하고 re-request 날려주세용!

2024-01-16 19:12 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/ClimberService.java
>          climber.setSocialType(SocialType.valueOf(socialType));
전에 말씀드렸듯이 세터대신 메소드를 생성하는 방식으로 변경해주세요~!

2024-01-16 19:12 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/ClimberService.java
> +        String profile_img = null;
가능하다면 스네이크케이스 대신 자바 컨벤션인 카멜케이스를 사용해주세요!

2024-01-16 19:12 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/NaverUserInfo.java
> +        System.out.println(profileImage);
디버깅때 사용한건가용..?

2024-01-16 19:12 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/NaverUserInfo.java
> +    public String getID() {
getID로 하신 이유가 있으실까요? 없다면 getId()로 변경해주세요~!

2024-01-16 19:12 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/climber/NaverUserInfo.java
> +            throw new RuntimeException("ID가 없거나 비어있습니다.");
될 수 있다면 스타일상 else를 피하는 것이 좋습니다! 
또한 예외case에 대해서는 독립된 if문으로 분리해서 처리하는, 앞쪽에 처리하는 얼리 리턴 방식을 사용하는 것이 가독성과 좋습니다
[if else문 클린코드](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90)
그리고 조건문 안에는 긍정의 조건이 있는것이 가독성이 더 좋습니다
수정을 하면 
`java
if(id == null || id.isEmpty()) {
    //예외 처리
}
return id;
`
이렇게 수정을 할 수 있을 것 같습니다~!

2024-01-17 00:54 UTC, Nesquitto approved these changes
멋집니다!! 수고하셨습니다!

2024-01-19 09:13 UTC, gourderased approved these changes

2024-01-19 15:21 UTC, merged