[SPR-82] 리뷰 수정 기능 구현 + CurrentUser 적용(Review Domain)
TheClimeet/climeet-spring pull request #44
Opened 2024-01-25 05:07 UTC by Nesquitto

## 요약
- 리뷰 수정 기능을 구현했습니다.
- Review Domain의 모든 기능에 CurrentUser 적용했습니다.

## 상세 내용

- 암장 리뷰 수정 기능을 구현했습니다.
``` java
@Transactional
    public void changeReview(CreateReviewRequest changeReviewRequest, User user) {
        // 리뷰 rating의 범위 확인
        if (changeReviewRequest.getRating() < 0 || changeReviewRequest.getRating() > 5
            || changeReviewRequest.getRating() % 0.5 != 0) {
            throw new GeneralException(ErrorStatus._RATING_OUT_OF_RANGE);
        }

        ClimbingGym climbingGym = climbingGymRepository.findById(
                changeReviewRequest.getClimbingGymId())
            .orElseThrow(() -> new GeneralException(ErrorStatus._EMPTY_CLIMBING_GYM));

        // 관리자가 등록된 암장인지 확인
        if (climbingGym.getManager() == null) {
            throw new GeneralException(ErrorStatus._EMPTY_MANAGER_GYM);
        }

        Climber climber = climberRepository.findById(user.getId())
            .orElseThrow(() -> new GeneralException(ErrorStatus._EMPTY_MEMBER));

        // 리뷰 데이터 불러오기
        Review review = reviewRepository.findByClimbingGymAndClimber(
                climbingGym, climber)
            .orElseThrow(() -> new GeneralException(ErrorStatus._EMPTY_REVIEW));

        // 리뷰 추가로 인한 평균 리뷰 갱신
        climbingGym.reviewChange(review.getRating(), changeReviewRequest.getRating());

        review.setRating(changeReviewRequest.getRating());
        review.setContent(changeReviewRequest.getContent());

        reviewRepository.save(review);
    }

```
위 Service에서 예외처리를 모두 한 뒤에, reviewChange 함수로 평균 리뷰를 갱신합니다.

``` java
public void reviewChange(Float beforeRating, Float afterRating) {
        this.sumRating -= beforeRating;
        this.sumRating += afterRating;
        this.averageRatingCalculate();
    }
```
위 코드로 평균 리뷰를 갱신합니다.

## 테스트 확인 내용

- Postman 및, Swagger로 모두 동작, 예외처리 확인 완료했습니다.

## 질문 및 이외 사항

- Service 단에서
``` java
        review.setRating(changeReviewRequest.getRating());
        review.setContent(changeReviewRequest.getContent());

        reviewRepository.save(review);
```
다음과 같이 setRating, setContent로 값을 수정하는데, 혹시 이 부분도 builder로 수정이 가능할까요??

2024-01-25 08:20 UTC, tjdgns8439 approved these changes
전반적으로 짜임새 있습니다!
이후에 delete구현할 때 review count만 수정만 조심하면 될 것 같네요!
setter보다는 review entity에 update함수를 추가해서 rating&content를 수정하는 방식으로 구현해도 좋을 것 같습니다!

참고: https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0

2024-01-25 08:21 UTC, gourderased requested changes
고생하셨습니다~~! 리뷰확인해주세욥

2024-01-25 08:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/review/ReviewService.java
> +        review.setContent(changeReviewRequest.getContent());
빌더는 사용하지 않고 보통 updateRating이런식으로 메소드를 만들어 사용합니다! @Setter는 거의 권장되지 않습니다!
[setter 사용 지양](https://climeet.retool.com/editor/3ce4832e-b9ce-11ee-a962-53136813254e/%EC%A7%80%EC%9A%B4%20%EB%B0%95%20-%20Jan%2023%2C%202024%20-%206%3A03%3A12PM) 이미 엔티티를 생성하고 값을 설정해야하는 경우 보통 updateRating? 이라는 메소드를 만들어 원하는 컬럼만 변경할 수 있게 해야합니다

2024-01-25 08:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/review/ReviewService.java
> +            || changeReviewRequest.getRating() % 0.5 != 0) {
매직넘버 대신 상수로 선언해주세요! 가독성이 더 좋아집니다
[매직넘버](https://velog.io/@hwisaac/%EB%A7%A4%EC%A7%81%EB%84%98%EB%B2%84)

2024-01-26 08:09 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/review/ReviewService.java
> +        review.setContent(changeReviewRequest.getContent());
아! 다른 좋은 방법이 있을까 고민 했었는데, 깨달아버렸습니다... 감사합니다!

2024-01-26 08:11 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/review/ReviewService.java
> +            || changeReviewRequest.getRating() % 0.5 != 0) {
상수로 선언하면서, 범위 확인이 생성, 수정 단에서 모두 사용되기 때문에 확인하는 함수를 따로 만들었습니다..! Service단에 만들고 적용했는데, 이렇게 작성해도 되는걸까요? 아니면 다른 파일을 하나 만들어서 사용을 해야하는게 좋은지는 잘 모르겠습니다...!

2024-01-26 08:11 UTC, Nesquitto commented
> 전반적으로 짜임새 있습니다! 이후에 delete구현할 때 review count만 수정만 조심하면 될 것 같네요! setter보다는 review entity에 update함수를 추가해서 rating&content를 수정하는 방식으로 구현해도 좋을 것 같습니다!
> 
> 참고: https://velog.io/@langoustine/setter-%EC%A7%80%EC%96%91-%EC%9D%B4%EC%9C%A0

확인했습니다! 자세한 설명 감사합니다!!

2024-01-26 08:32 UTC, gourderased approved these changes

2024-01-26 08:33 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/review/ReviewService.java
> +            || changeReviewRequest.getRating() % 0.5 != 0) {
상수가 더 많아진다면 파일을 만들어 사용하는 게 나을 것 같기도합니다! 리팩토링 목록에 적어둘게요!

2024-01-26 09:43 UTC, merged