[
TheClimeet/climeet-spring pull request #50
Opened 2024-01-29 06:33 UTC by Nesquitto

## 요약
음... 
-

## 상세 내용

- ex) 코드의 흐름이나 중요한 부분을 작성해주세요.
- ex) 기존 calculate 함수의 버그를 수정했습니다.

## 테스트 확인 내용

- ex) 테스트 코드의 내용을 작성해주세요.
- ex) caculate() 함수의 입력값에 대한 테스트를 작성, 일치하는지 확인했습니다.

## 질문 및 이외 사항

- ex) 이 부분에서 쿼리가 너무 많이 날라가는 것 같은데 좋은 방법 있을까요?

2024-01-29 13:22 UTC, gourderased requested changes
많이 작성하셨네요 수고많으셨습니다 ㅎ 질문남겼으니 확인해주세여~!

2024-01-29 13:22 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
위에서 생성한 루트를 db에서 불러오는 코드 맞나용?

2024-01-29 13:22 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionConverter.java
> +    public static List<Long> convertStringToList(String stringToConvert) {
컨버터 생성과 주석 좋습니당ㅎ

2024-01-29 13:22 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
repository코드에서 Optional에 담아 반환하면 orElseThrow문 사용이 가능합니다! Optional내 객체를 꺼내려면 .get()으로 꺼낼 수 있습니다!

2024-01-29 14:06 UTC, tjdgns8439 approved these changes
상당히 고생하셨습니다..
진로가 언급한 것처럼 List에 대해 Optional로 반환하여 orElseThrow()를 사용하면 더 깔끔해질 것 같습니다!

2024-01-29 14:06 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
저도 이 부분 궁금하네요!

2024-01-29 15:06 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
넵 맞습니다!! 생성한 루트 Id를 프론트에 반환해줘야, RouteVersion을 생성을 요청할 때 수정된 IdList를 받을 수 있을 것이라고 생각했습니다!
혹시 더 나은 방법으로 Id를 반환하는 방법이 있을까요?!

2024-01-29 15:39 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
오 그런가요?? Optional이 생각보다 더 범용적으로 쓰이는군요??! 감사합니다!!

2024-01-29 15:51 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
Optional<List<RouteVersion>>을 사용해서 orElseThrow를 사용하려고 하였는데, 예외처리 없이 빈 배열이 반환됩니다...!
혹시 위처럼 바꿔달라고 하는것이 맞는걸까요??
찾아보니 Optional<List<>>의 형식은 List는 없어도 빈 배열을 반환하기 때문에 Optional의 의미가 없다고 합니다!
[해당 링크에서 봤습니다](https://velog.io/@hnsoo/JPA-%EC%9E%98%EB%AA%BB%EB%90%9C-%ED%91%9C%ED%98%84-OptionalListobject)

2024-01-29 15:55 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
헉.. 그렇다면 진로가 말한 게 제가 언급한 것과 다를 수도 있겠군요.. 저도 적용해보지 않고 깔짝 검색하고 말씀드린 거라 잘못된 정보일 수도 있겠네요ㅜㅜ 죄송합니다 짧은 식견을 토대로 드린 무지성코멘트..🥲

2024-01-29 15:59 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
생각해보니 List의 경우 repository에서 조회할 때 기본적으로 에러로 처리하지 않기 때문에 orElseThrow가 되지 않겠네요.. 저도 더 서치해보겠습니다.

2024-01-29 15:59 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
아닙니다~~ 이번 기회로 Optional의 특징에 대해서 또 알게 되었으니 식견이 넓어진거죠 ㅎㅎ

2024-01-29 16:13 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
그렇다면 routeRepository.save()의 반환형이 어떻게 되는지 알아보시면 좋을 것 같습니다~~~!

2024-01-29 16:19 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
[save반환 ](https://velog.io/@mincho920/JpaRepository%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%A0-%EB%95%8C-save-%EB%A9%94%EC%86%8C%EB%93%9C%EA%B0%80-%EA%B0%9D%EC%B2%B4%EB%A5%BC-%EB%B0%98%ED%99%98%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-01-29 16:21 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/routeversion/RouteVersionService.java
> +        List<RouteVersion> routeVersionList = routeVersionRepository.findByClimbingGymOrderByTimePointDesc(
헉 맞네요! List는 null이 들어가지 않아서 .isEmpty()로 처리하는게 맞습니다! 아무 생각없이 Optional을 남발해서는 안되겠군요 죄송합니당ㅎ

2024-01-29 16:21 UTC, gourderased approved these changes

2024-01-30 03:08 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/route/RouteService.java
> +        Route route = routeRepository.findByRouteImageUrl(routeImageUrl);
헐 save 반환값이 저장된 route 그 자체였군요...? id 뺀 객체를 반환하는줄 알았는데... 감사합니다!!
핑프였습니다... 감사합니다...ㅎㅎ

2024-01-30 04:10 UTC, yerim216 approved these changes
엄청 자세히 적어주셨네요!!
변경된 내용이 많았는데도 이해하기 쉬웠습니다
고생하셨어요!

2024-01-30 05:07 UTC, merged