[SPR-74] 암장 크롤링 데이터 DB 저장 및 반환 기능 구현
TheClimeet/climeet-spring pull request #60
Opened 2024-01-31 07:22 UTC by Nesquitto

## 요약
- 암장 크롤링 데이터를 파싱해서 DB에 저장하고 반환하는 기능 구현입니다.

## 상세 내용
1. Lambda에서 암장 데이터를 가져옵니다.
2. 가져온 데이터는 다음과 같습니다.
``` json
{
    "name": "홍성클라이밍센터",
    "tel": "010-3389-8848",
    "address": "충청남도 홍성군 홍북읍 봉신리 290-13 2층",
    "businessHours": {
        "수": [
            "16:00",
            "22:00"
        ],
        "목": [
            "16:00",
            "22:00"
        ],
        "금": [
            "16:00",
            "22:00"
        ],
        "월": [
            "16:00",
            "22:00"
        ],
        "화": [
            "16:00",
            "22:00"
        ]
    }
}
```
3. 해당 값을 String으로 받아오고, 받아온 데이터를 파싱하여  DB에 넣음과 동시에 파싱한 값을 반환합니다.

## 테스트 확인 내용
<img width="754" alt="스크린샷 2024-01-31 오후 4 16 47" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/02cf55b1-39f7-4ad4-b403-5405155360a0">
<img width="755" alt="스크린샷 2024-01-31 오후 4 17 04" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/9d2b4ad0-5266-4430-a878-1a3ff6714f0b">
<img width="746" alt="스크린샷 2024-01-31 오후 4 17 19" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/cd545a83-08c0-423a-b88f-dbda9cda0347">

다음과 같습니다!

DB에 저장되는 값은 다음과 같습니다!
<img width="767" alt="스크린샷 2024-01-31 오후 4 18 17" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/8cb17c1b-741c-4830-b9d8-6293b7179188">

값이 없을 때에는 빈 문자열 값을 저장할 것이며, businessHours는 빈 배열을 반환할 것입니다.
또한 정기휴일과 같이 운영시간이 없는 경우에는 해당 일자가 입력되지 않습니다.
- 빈 문자열 반환
<img width="743" alt="스크린샷 2024-01-31 오후 4 20 39" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/30215612-c61e-49ab-966c-6ff1e3cb5519">
- 영업일자 없을 때
<img width="512" alt="스크린샷 2024-01-31 오후 4 21 00" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/83d46199-7bd4-4ce3-9d04-1f84ac0477b0">
이상입니다.

## 질문 및 이외 사항

2024-01-31 07:27 UTC, Nesquitto commented
아 Service 단에 name 관련해서 주석이 존재하는데, 이건 값을 가져오긴 하지만, 현재는 사용하지 않아서 언젠가 쓰지 않을까 하는 마음에 일단 주석으로 처리해뒀습니다.

+ ApiError 관련해서 정의하지 않은 것은 후에 미리가 Service만 사용할 것 같다고 하여 임시로 만든 메서드이기 때문입니다!

2024-02-01 04:58 UTC, tjdgns8439 requested changes

2024-02-01 04:58 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/climbinggym/ClimbingGymService.java
> +        String callUrl = "https://i9jkabugud.execute-api.ap-northeast-2.amazonaws.com/dev/gym?word="
URL 도 환경변수로 설정하는 것이 좋을 것 같습니다!

2024-02-01 05:14 UTC, gourderased approved these changes
고생하셧습니닷

2024-02-01 07:23 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/climbinggym/ClimbingGymService.java
> +        String callUrl = "https://i9jkabugud.execute-api.ap-northeast-2.amazonaws.com/dev/gym?word="
변경했습니다!!

2024-02-01 10:58 UTC, yerim216 approved these changes
고생하셨습니다!!
(잘 사용하겠습니다~~~~)

2024-02-02 08:10 UTC, merged