[SPR-118] 유저 팔로우/언팔로우 기능 구현
TheClimeet/climeet-spring pull request #70
Opened 2024-02-02 07:45 UTC by yerim216

## 요약
-유저 팔로우, 언팔로우 API를 개발하였습니다

## 상세 내용

- FollowRelationshipController에 두 가지 API가 존재합니다

**1. 유저를 팔로우 하는 API**

  ``` java
  @PostMapping("/follow/{userId}")
    @Operation(summary = "유저 팔로우")
    @SwaggerApiError({ErrorStatus._EMPTY_USER, ErrorStatus._EXIST_FOLLOW_RELATIONSHIP})
    public ResponseEntity<String> followUser(@RequestParam Long followingUserId, @CurrentUser User currentUser){
        User followingUser = userRepository.findById(followingUserId)
                .orElseThrow(()-> new GeneralException(ErrorStatus._EMPTY_USER));
        if(followRelationshipRepository.findByFollowerIdAndFollowingId(currentUser.getId(), followingUserId).isPresent()) {
            throw new GeneralException(ErrorStatus._EXIST_FOLLOW_RELATIONSHIP);
        }
        followRelationshipService.createFollowRelationship(currentUser, followingUser);
        return ResponseEntity.ok("팔로우 완료");
    }

```

**2. 유저 팔로우 취소 API**

    ```java
@DeleteMapping("/unfollow/{userId}")
    @Operation(summary = "유저 팔로우 취소")
    @SwaggerApiError({ErrorStatus._EMPTY_USER, ErrorStatus._EXIST_FOLLOW_RELATIONSHIP})
    public ResponseEntity<String> unfollowUser(@RequestParam Long followingUserId, @CurrentUser User currentUser){
        userRepository.findById(followingUserId)
            .orElseThrow(()-> new GeneralException(ErrorStatus._EMPTY_USER));
        FollowRelationship followRelationship = followRelationshipRepository.findByFollowerIdAndFollowingId(currentUser.getId(), followingUserId)
            .orElseThrow(()-> new GeneralException(ErrorStatus._EMPTY_FOLLOW_RELATIONSHIP));
        followRelationshipService.deleteFollowRelationship(followRelationship);
        return ResponseEntity.ok("팔로우 취소 완료");
    }
```

서비스 로직은 다음과 같습니다

- createFollowRelationship의 경우 FollowRelationship 객체를 생성합니다

```java
public void createFollowRelationship(User follower, User followee) {
        FollowRelationship followRelationship = FollowRelationship.toEntity(follower, followee);
        followRelationshipRepository.save(followRelationship);
        follower.increaseFollwerCount();
    }
```

- deleteFollowRelationship의 경우 FollowRelationshipRepository의 deleteById를 이용하여 레코드를 삭제합니다.

```java
    public void deleteFollowRelationship(FollowRelationship followRelationship){
        followRelationshipRepository.deleteById(followRelationship.getId());
        followRelationship.getFollower().decreaseFollwerCount();
    }
```

## 테스트 확인 내용
세 가지의 예외 처리를 작성하였습니다.

1. 팔로우 관계 생성 시 -> 이미 팔로우 관계가 존재하는 경우
2. 팔로우 관계 삭제 시 -> 팔로우 관계가 존재하는 경우
3. 공통 : 유저가 존재하지 않는 경우

더미데이터 삽입과 Swagger 시행을 통해 모두 적절히 예외처리가 처리됨을 확인하였습니다. 

## 질문 및 이외 사항

2024-02-02 11:00 UTC, gourderased requested changes
고생하셨습니다! 리뷰확인해주세용

2024-02-02 11:00 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/followrelationship/FollowRelationshipController.java
> +            throw new GeneralException(ErrorStatus._EXIST_FOLLOW_RELATIONSHIP);
예외처리 꼼꼼히 해주셨네요! 다만 제 생각에는 서비스 계층에서 하는 것이 나아보입니다! 컨트롤러안에 있는 검증은 다른 컨트롤러에서 활용할 수 없습니다
서비스에 함수로  생성을 한다면 추후 다른 컨트롤러 함수에서도 이용이 가능할 것 같습니다! 
다음으로 분리원칙에 따라 컨트롤러에서는 api요청과 응답 관련 코드만 있는 것이 책임이 명확히 분리될 것 같습니다! 
혹시 의견있으시면 말씀해주세용~!

2024-02-02 11:00 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/followrelationship/FollowRelationshipController.java
> +    @DeleteMapping("/unfollow/{userId}")
마찬가지입니다 Delete에 이미 삭제라는 의미가 있으니 unfollow라는 행위보다 명사로 작성해주세욥!

2024-02-02 11:00 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/followrelationship/FollowRelationshipController.java
> +    @PostMapping("/follow/{userId}")
행위보다는 RESTful한 방식으로 설계하면 좋을 것 같아요? 예시로 `Post/users/{userId}followers` 가 어떨까싶습니당~~!

2024-02-04 01:18 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/followrelationship/FollowRelationshipController.java
> +            throw new GeneralException(ErrorStatus._EXIST_FOLLOW_RELATIONSHIP);
저도 같은 생각입니다!

2024-02-04 01:23 UTC, tjdgns8439 approved these changes
진로가 요청한 "서비스와 컨트롤러의 책임 분리" 부분만 수정해주시면 제 기준에는 머지해도 좋을 것 같습니다!

2024-02-04 11:49 UTC, Nesquitto approved these changes
위의 언급된 사항 외에는 문제 없어보입니다! 수고하셨습니당~

2024-02-05 12:30 UTC, gourderased requested changes
이따 집가서 보겠습니당~~!

2024-02-05 12:30 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/user/UserController.java
> +    @GetMapping("/get-following")
유 게릿?

2024-02-05 12:31 UTC, Nesquitto approved these changes
LGTM!

2024-02-08 06:23 UTC, merged