[SPR-137] 암장 기능 관련 수정 및 추가
TheClimeet/climeet-spring pull request #78
Opened 2024-02-05 11:14 UTC by Nesquitto

## 요약
- 암장 배경 이미지 반환 변경
- 암장 정보(탭) 조회 구현
<img width="270" alt="스크린샷 2024-02-05 오후 8 08 13" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/2a17a211-933f-453c-812e-adb53311c221">

## 상세 내용

- 암장 배경 이미지 반환 변경
기존에 이해를 잘못해서 manager의 profileImage를 가져왔었는데, backgroundImage라는 테이블이 있다는 것을 깨달았습니다.
따라서 List<String>을 가져오도록 수정했고, 테이블에서 데이터를 가져오도록 수정했습니다.
Service단에서의 수정사항
``` java
List<ClimbingGymBackgroundImage> backgroundImageList = climbingGymBackgroundImageRepository.findByClimbingGym(
            climbingGym);
        if (backgroundImageList.isEmpty()) {
            throw new GeneralException(ErrorStatus._EMPTY_BACKGROUND_IMAGE_LIST);
        }
        List<String> backgroundImageUrlList = backgroundImageList.stream()
            .map(ClimbingGymBackgroundImage::getImgUrl)
            .toList();
```

- 암장 정보(탭) 조회 구현
<img width="270" alt="스크린샷 2024-02-05 오후 8 08 13" src="https://github.com/TheClimeet/climeet-spring/assets/62535229/2a17a211-933f-453c-812e-adb53311c221">

위의 화면에서 보이는 Service목록과 크롤링한 정보를 반환하도록 수정했습니다.
간단하니 코드로 바로 이해 가능할 것입니다..!

``` java
    ObjectMapper objectMapper = new ObjectMapper();
        try {
            Map<String, List<String>> businessHoursMap = objectMapper.readValue(
                climbingGym.getBusinessHours(),
                new TypeReference<Map<String, List<String>>>() {
                });
            return ClimbingGymTabInfoResponse.toDto(climbingGymRepository.save(climbingGym),
                businessHoursMap, serviceList);
        } catch (Exception e) {
            throw new GeneralException(ErrorStatus._ERROR_JSON_PARSE);
        }
```
위 코드는 테이블에
``` json
{"금": ["16:00", "22:00"], "목": ["16:00", "22:00"], "수": ["16:00", "22:00"], "월": ["16:00", "22:00"], "화": ["16:00", "22:00"]}
```
위와같이 저장되어있는 json 데이터를 파싱해서 가져오도록 합니다.

## 테스트 확인 내용

- 암장 상단 데이터 불러오기
``` json
{
    "gymProfileImageUrl": "프로필이미지유알엘",
    "gymBackGroundImageUrl": [
        "qwerqwerqwer",
        "asdfasdf"
    ],
    "gymName": "홍성클라이밍센터",
    "followerCount": 50310,
    "followingCount": 30300,
    "averageRating": 1.0,
    "reviewCount": 4
}
```

- 암장 탭 데이터 불러오기
``` json
{
    "gymId": 1,
    "address": "충청남도 홍성군 홍북읍 봉신리 290-13 2층",
    "tel": "010-3389-8848",
    "businessHours": {
        "금": [
            "16:00",
            "22:00"
        ],
        "목": [
            "16:00",
            "22:00"
        ],
        "수": [
            "16:00",
            "22:00"
        ],
        "월": [
            "16:00",
            "22:00"
        ],
        "화": [
            "16:00",
            "22:00"
        ]
    },
    "serviceList": [
        "샤워_시설",
        "샤워_용품",
        "수건_제공",
        "간이_세면대",
        "초크_대여",
        "암벽화_대여",
        "삼각대_대여",
        "운동복_대여"
    ]
}
```
 

## 질문 및 이외 사항

- 의견 감사합니다.

2024-02-07 06:30 UTC, tjdgns8439 approved these changes
LGTM

2024-02-07 08:22 UTC, yerim216 requested changes
고생하셨습니다!! 
암장 리스트에 대한 코멘트 남겼는데 확인 부탁드려요!

2024-02-07 08:22 UTC, yerim216 commented on src/main/java/com/climeet/climeet_backend/domain/climbinggym/ClimbingGymService.java
> +        return ClimbingGymDetailResponse.toDto(climbingGym, manager, backgroundImageUrlList);
배경사진이 여러 개인데, 피그마 봤을 때 화면 상에는 대표 사진이 한 장밖에 없는 것 같아서
여러 개 배경 사진 중에 어떤 사진을 대표 사진으로 선택할 것인지에 대한 부분이 필요할 것 같아요!

2024-02-07 12:47 UTC, gourderased approved these changes
크롤링으로 가져온 데이터 변환하는 부분 좋네요 고생하셨습니당!

2024-02-08 05:09 UTC, Nesquitto commented on src/main/java/com/climeet/climeet_backend/domain/climbinggym/ClimbingGymService.java
> +        return ClimbingGymDetailResponse.toDto(climbingGym, manager, backgroundImageUrlList);
이전에 여러개 들어갔던걸 봤던 느낌이 있어서 그렇게 했는데, 지금 보니까 그렇네요?!
피그마에 하나인지 여러개인지 질문을 남겼고, 여러개가 들어간다고 하면, 대표 이미지 설정에 관한 WF도 물어보겠습니다!
의견 감사합니다!!

2024-02-08 06:38 UTC, merged