[SPR-128] 쇼츠 프로필 초록불 관련 작업
TheClimeet/climeet-spring pull request #88
Opened 2024-02-08 10:09 UTC by yerim216

## 요약
![image](https://github.com/TheClimeet/climeet-spring/assets/85860891/5a4c2cf1-ca1b-4327-a7a5-c847910e3969)
팔로우 하고 있는 유저의 프로필을 조회하는 화면에서 유저가 최근에 쇼츠를 올렸다면 초록불이 생기고, 
유저가 프로필을 클릭 하거나, 3일이 지나면 초록불이 사라지는 함수를 구현하였습니다. 
(프로필을 조회하는 함수는 이전에 구현 하였습니다)

## 상세 내용
- 스케줄링을 이용하였습니다. 초록불 상태 컬럼은 followRelationship 테이블에 존재하기 때문에, 컬럼의 상태를 바꿔주기 위해서는 followRelationship 테이블의 순회가 필요합니다. 지금은 컬럼이 많지 않지만, 추후에 많아진다면 비효율적일 수도 있을 것 같아서 스케줄링 사용 여부를 고민 하였지만, 결론적으로 스케줄링을 사용하게 되었습니다.
- 대안적으로 고민한 방법은 async + 스케줄링을 이용하는 방법이었습니다. 쇼츠를 업로드 하는 시점에 3일 뒤에 상태를 false로 바꿔주는 스케줄링 함수를 시작하는 방법이었습니다. 다만, async는 서버가 재시작 되거나 종료되는 경우, 상태를 유지하지 못하는 큰 문제점이 있기 때문에 결론적으로 주기적으로 순회하는 스케줄링 방식으로 코드를 작성 하였습니다. 

## 테스트 확인 내용
- 디버거를 통해 스케줄링이 정해진 시간(현재 코드는 1분, 그러나 10분 정도로 바꾸는 것도 괜찮을 것 같다고 생각이 드네요.) 마다 수행되는 것을 확인 하였습니다. (주기적으로 순회하는 스케줄링 기간은 논의 후 확정하면 좋을 것 같습니다)
- 쇼츠 업로드 시간을 불러온 후, 3일 이상이면 상태를 false로 만드는 것을 확인 했습니다. 
- 쇼츠 업로드 시 FollowRelationship 엔티티의 isUploadShortsRecent 컬럼이 true로 변경되는 것을 확인했고, 3일이 지나있다면 false로 바뀌는 것 또한 확인 했습니다. 

## 질문 및 이외 사항

- followRelationship 테이블을 순회하는 함수를 몇 분 간격으로 수행하면 좋을지 함께 논의하면 좋을 것 같습니다. 1분마다 수행하는 것이 가장 정확하겠지만, 부하테스트를 수행해봐도 좋을 것 같습니다!

2024-02-09 11:09 UTC, tjdgns8439 requested changes
리뷰 읽어주세요!

2024-02-09 11:09 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/shorts/ShortsService.java
> +        for(Shorts shorts : shortsList) {
흠.. 일단 3일 전에 저장된 모든 데이터를 가져온 후 해당 쇼츠들을 for문으로 도는 것은 오버헤드가 꽤 심할 것으로 생각됩니다.
또한 해당 쇼츠를 올린 FollowRelationship을 2중 for문의 형태로 도는 것은 훨씬 오버헤드가 클 것으로 예상이 됩니다.

일단 가장 먼저 생각할 수 있는 것은 가장 naive한 방법으로 
1. ~~for문 -> stream()~~ (지운 이유는 아래에 서술)
2. 3일 전 이전의 쇼츠들말고 세부적으로 기간을 더 추가하는 것이 맞을 것 같습니다.(이 전의 데이터들은 정상적으로 작동했다면 이미 이전 스케줄러에 의해서 꺼졌다고 가정하기 때문)

+ 추가로 해당 코드를 동작시키면 1분마다 작동할 것입니다.
+ 따라서 동작이 제대로 작동한다는 것을 확인하셨으면 적어도 며칠로 늘려서 굳이 현재 필요하지 않은 사용을 제한해주세요!


https://sigridjin.medium.com/java-stream-api%EB%8A%94-%EC%99%9C-for-loop%EB%B3%B4%EB%8B%A4-%EB%8A%90%EB%A6%B4%EA%B9%8C-50dec4b9974b
**저는 무조건 stream이 for문보다 빠를 것이라고 생각했습니다.**
- 하지만 원시타입이라면 for문이 훨씬 더 빠르고 컬렉션 타입이어야 속도가 비슷해진다는 글을 보았습니다..
- 여러분이 알고 계신 개념은 어떠신가요? 함께 얘기나눠보고 싶습니다!

2024-02-09 11:09 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/shorts/ShortsService.java
> +            System.out.println(shorts);
요것도 지워주세요 ㅎㅎ

2024-02-10 04:47 UTC, gourderased requested changes

2024-02-10 04:47 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/shorts/ShortsService.java
> +        for(Shorts shorts : shortsList) {
스트림의 병렬 처리 기능이 초기 설정 비용 때문에 작은 데이터에 대해 for문이 적은 데이터에서 유리하다고 알고있습니다.
위 코드 상으로는 직접비교를 해봐야알것같네요!
+ 1분은 테스트용인거 맞나요?

2024-02-10 04:49 UTC, gourderased commented on src/main/java/com/climeet/climeet_backend/domain/followrelationship/FollowRelationship.java
A유저가 B유저를 팔로우했을 때 B유저가 영상을 3일 이내로 올린 상황이라면 확인해서 true로 바꿔야할 것 같습니다!

2024-02-10 04:58 UTC, tjdgns8439 commented on src/main/java/com/climeet/climeet_backend/domain/shorts/ShortsService.java
> +        for(Shorts shorts : shortsList) {
테스트용아니고 실제 코드라고 생각합니다!

2024-02-10 05:02 UTC, tjdgns8439 commented
문득 치명적인 결함을 발견했습니다.
만약 영상을 2/10, 2/9, 2/8일에 올렸다고 가정해보겠습니다.
그럼 2/11이 되면 2/8일의 데이터가 3일 전으로 적용되기 때문에 해당 팔로우 관계에 있는 유저들에게는 false로 업데이트 될 겁니다.
하지만 2/9, 2/10일의 데이터는 아직 그린라이트 상태여야 합니다.
이에 따라 isUploadShortsRecent 필드와 함께 가장 최근에 추가된 날짜도 기록해놔야 할 것 같습니다!

2024-02-11 04:50 UTC, yerim216 commented on src/main/java/com/climeet/climeet_backend/domain/shorts/ShortsService.java
> +        for(Shorts shorts : shortsList) {
for문과 stream 중 어떤 것을 사용할지는 실제로 테스트를 해봐야할 것 같습니다
3일 이전이라고 가정한 이유는 스케줄러가 도는 기간이 엇갈릴 수도 있어서 그렇게 한 것인데, 
딱 3일 데이터만 찾으면 1분 단위로 스케줄러가 돌 때 3일 1분 전이면 못잡아낼까봐 3일 이전으로 넓게 설정한 것입니다!
스케줄러가 도는 시간을 정확하게 결정하면, 예를 들면 10분이라고 설정했으면 3일 9분 전~3일 이런식으로 범위를 설정할 수 있을 것 같습니다,,,,,

2024-02-14 05:11 UTC, gourderased approved these changes

2024-02-14 05:19 UTC, merged